SELECT A.APNT_NO APNTNO, P.PT_NAME PTNAME, P.PT_NO PTNO, D.MCDP_CD MCDPCD, D.DR_NAME DRNAME, A.APNT_YMD APNTYMD
FROM APPOINTMENT A 
    JOIN PATIENT P ON P.PT_NO = A.PT_NO
    JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE 
    A.APNT_CNCL_YMD IS NULL 
    AND A.MCDP_CD = 'CS'
    AND DATE(A.APNT_YMD) = '2022-04-13' 
ORDER BY 
    A.APNT_YMD;
    
