SELECT DISTINCT rc.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS rc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh ON rc.CAR_ID = rh.CAR_ID
WHERE rc.CAR_TYPE = '세단'
    AND DATE_FORMAT(rh.START_DATE, '%m') = '10'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC